version: '3.3'

services:

    db:
        image: mysql:5.7     
        container_name: app-database
        restart: always     
        volumes:
            - volume-db:/var/lib/mysql                 
        ports:
            - "3320:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: databasename
            MYSQL_USER: user
            MYSQL_PASSWORD: 123

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: app-phpmyadmin    
        depends_on:
            - db
        restart: always
        ports:
            - "8888:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db                

    php:        
        image: nanoninja/php-fpm
        container_name: app-php
        command: php -v
        restart: always        
        depends_on:
            - db                
        working_dir: /var/www
        volumes:
            - .:/var/www            
        ports:
            - 8080:8080             

volumes:    
    volume-db: